### ISSUE TITLE
Angular 4 compatibility

### ISSUE THREAD

**Issue by merwok** [ngx-translate/i18n-polyfill#12]
Hello!  We wanted to translate some strings outside of templates and found out this project.
Because we are using ionic, the angular components are at version 4, so loading this polyfill fails.

Would it be possible to make it compatible with angular 4 and 5?

**Comment by ocombe** [comment]
Not really, I had to copy and edit a lot of the `@angular/compiler` package files manually to make this work (since most of the code that I use is not exported), it would be too much work for me to do that from a clean v4 code base.

**Comment by merwok** [comment]
Thank you for the reply.  Time to fight our dependencies to upgrade!
