### ISSUE TITLE
XLIFF `source-language` attribute gets replaced by `en`

### ISSUE THREAD

**Issue by alfaproject** [ngx-translate/i18n-polyfill#15]
As the title says the `source-language` attribute is not preserved from the original XLIFF file:
`ng xi18n --locale=af`

`af` gets replaced by `en` after running `ngx-extractor`

**Comment by intellix** [comment]
Seems the problem is caused by here: https://github.com/ngx-translate/i18n-polyfill/blob/159c0a8402d9dbb1fe800445c15cfd974ba69a39/lib/extractor/src/extractor.ts#L166

**Comment by ocombe** [comment]
can you do both? pass it via cli, and if not then try to read it if the file exists, otherwise use "en"

**Comment by ocombe** [comment]
v0.2.0 and v1.0.0 (for Angular v6) released with this change
