### ISSUE TITLE
"**" in cli Parameter -i

### ISSUE THREAD

**Issue by BSchuhmacher** [ngx-translate/i18n-polyfill#2]
Hi
It seems as directory wildcard with the "input" options do not work as (I) expected. A "**" as a directory wildcard should work through all subdirectories, but it seems as only a depth of one is handled.

As you are using yargs for handling the options the problem might be found there.

As a work around I just put the "input" option between quotation marks. After that getAst did the job of handling the wildcard.

**Comment by ocombe** [comment]
That's weird, I use that in my tests `example/src/**/*.ts`: https://github.com/ngx-translate/i18n-polyfill/blob/master/test/extractor.spec.ts#L5

**Comment by BSchuhmacher** [comment]
I checked the matter again with the same result. But I checked on another PC, where the result is as expected. So it seems to be a problem with the OS.
The PC that is working through all subdirectories runs WIndows 8.1, the one which only runs up to a depth of 1 runs Ubuntu 16.04.
Maybe Ubuntus bash (Version 4.3.48) expands the given option to all first level directories before it is given to the script as long as the input parameter is not enclosed in quotation marks.

Regards
Bernd

**Comment by BSchuhmacher** [comment]
Spending some more minutes I found out the following:
If you want to use globstar ('**') in the expected way on a bash running system you need to enable "Globstar with 
`shopt -s globstar`
Globstar is available for the running session then. If you want it anytime you need to edit you ~/.bashrc.
If you don't like the idea of turning on Globstar you need to put the input into quotations marks.
If you put input into quotation marks globbing is done by the getAst function.

Regards
Bernd

**Comment by fredrikredflag** [comment]
Mac OS have a similar issue:

This will only look in folders that are a direct descendent of `src`. 

```ngx-extractor -i src/**/*.ts -f xlf -o src/locale/messages.xlf```

To check all sub-directories use:
```ngx-extractor -i "src/**/*.ts" -f xlf -o src/locale/messages.xlf```
