### ISSUE TITLE
How to change the language at runtime

### ISSUE THREAD

**Issue by ThomasCybulski** [ngx-translate/i18n-polyfill#33]
Hey, I'm doing a bit research and I want to change the language of my project at runtime. I've tried the following code of the readme:

```javascript
{
provide: TRANSLATIONS,
   useFactory: (locale) => {
   locale = locale || 'de-DE';
      return require(`raw-loader!../assets/i18n/messages.${locale}.xlf`);
   },
   deps: [LOCALE_ID]
},
```

In my translate service is a function, to change the language, but without an effect.

```javascript
setEnLanguage() {
    registerLocaleData(localeEn);
}
```

I'm thankful for any help!

**Comment by mattiLeBlanc** [comment]
Have a look at what I did: 
https://github.com/angular/angular/issues/24549#issuecomment-402013622

It works, only issue I have is the the require doesn't survive the build process when I use `--prod` in the CLI. Havent found a solution yet.

**Comment by ThomasCybulski** [comment]
Thanks for your answer!
The solution looks a bit hackish, I think for now, I have to wait for Angular 7.x.

**Comment by mattiLeBlanc** [comment]
@ThomasCybulski It is not that hackish mate. It loads the XLF before it bootstraps your angular app.
I asked the Angular team and they said that for now this is the best way to move forward.
Up to you.
