### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by vqoph** [ngx-translate/i18n-polyfill#5]
cli version 1.6.0 
angular version 5.1.0
OS : OSX High sierra - 10.13.2 (17C88)

error on command `ngx-extractor  -i src/**/*.ts -f xlf -o src/i18n/source.xlf`

the error `env: node\r: No such file or directory`
in file `./lib/extractor/ngx-extractor.ts`

How to fix that : https://github.com/nwjs-community/nw-builder/issues/75#issuecomment-55108563

**Comment by ocombe** [comment]
can you try with quotes like this: `ngx-extractor -i "src/**/*.ts" -f xlf -o "src/i18n/source.xlf"` ?

**Comment by vqoph** [comment]
same error  :
```
$ yarn extract
yarn run v1.3.2
$ ngx-extractor  -i "src/**/*.ts" -f xlf -o "src/i18n/source.xlf"
env: node\r: No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
It's look like an encryption erro

**Comment by vqoph** [comment]
it's work with : 
```
./node_modules/@ngx-translate/i18n-polyfill/extractor/ngx-extractor -i "src/**/*.ts" -f xlf -o src/i18n/source.xlf
```

**Comment by vqoph** [comment]
the workaround work, but the issue is not fixed the file still encoded in DOS

**Comment by ocombe** [comment]
I've just pushed the fix, new release inc

**Comment by vqoph** [comment]
thx

**Comment by ocombe** [comment]
Can you try v0.1.1 please?

**Comment by vqoph** [comment]
Tested with  0.1.1 and `ngx-extractor` command work as expected thank you
