### ISSUE TITLE
Get error when compiling Angular 8 from cmd.exe in windows

### ISSUE THREAD

**Issue by bfis108137** [ngx-translate/i18n-polyfill#61]
If you use the polyfill in an Angular 8 project and you compile with the command prompt then you will get the error 

> TypeError: this._input.charCodeAt is not a function

It works in git bash and vscode but we need the command line for our Jenkins pipeline.  We have tried a number of ways to use the git bash from the command line but we get the same result.  Only opening the git bash manually and then compiling will avoid the error.

I have created a sample project to reproduce the error at 
[https://github.com/bfis108137/Angular8-i18-PolyFill-Bug](https://github.com/bfis108137/Angular8-i18-PolyFill-Bug)

In the sample project I have included a compiled version in the folder distCmd using the command line in case you are on mac or linux.  

Below is the console output:

> 
>   | (anonymous) | @ | main.ts:12
> -- | -- | -- | --
>   | invoke | @ | zone-evergreen.js:359
>   | run | @ | zone-evergreen.js:124
>   | (anonymous) | @ | zone-evergreen.js:855
>   | invokeTask | @ | zone-evergreen.js:391
>   | runTask | @ | zone-evergreen.js:168
>   | drainMicroTaskQueue | @ | zone-evergreen.js:559
>   | Promise.then (async) |   |  
>   | scheduleMicroTask | @ | zone-evergreen.js:542
>   | scheduleTask | @ | zone-evergreen.js:381
>   | scheduleTask | @ | zone-evergreen.js:211
>   | scheduleMicroTask | @ | zone-evergreen.js:231
>   | scheduleResolveOrReject | @ | zone-evergreen.js:845
>   | then | @ | zone-evergreen.js:955
>   | bootstrapModule | @ | core.js:40599
>   | ./src/main.ts | @ | main.ts:11
>   | __webpack_require__ | @ | bootstrap:79
>   | 0 | @ | main.ts:12
>   | __webpack_require__ | @ | bootstrap:79
>   | checkDeferredModules | @ | bootstrap:45
>   | webpackJsonpCallback | @ | bootstrap:32
>   | (anonymous) | @ | main.js:1
> 
>

**Comment by nrone** [comment]
Is fixed in this https://github.com/ngx-translate/i18n-polyfill/issues/60 - add .default to your require
