### ISSUE TITLE
How to define ids

### ISSUE THREAD

**Issue by axtho** [ngx-translate/i18n-polyfill#8]
How can one define own ids, as in @@my.title, instead of the hash value?

**Comment by ocombe** [comment]
You can call the service with a string or with an object which lets you define the id:

```ts
// simple string
i18n("This is a test {{myVar}} !", {myVar: "^_^"})

// object
i18n({
  value: "This is a test {{myVar}} !"
  id: "customid",
  meaning: "optional meaning",
  description: "optional desc"
}, {myVar: "^_^"});
```

**Comment by axtho** [comment]
ah, right ... as it says in the readme *facepalm*. Thanks.

**Comment by suchg** [comment]
I am facing an error while defining customId as "Missing translation for message "customId" ("[ERROR ->]Some value"): 0:0"
below is my code 
...
...
constructor( private elm: ElementRef,
               private i18n: I18n ) {
    this.customId = this.i18n({id: "customId", value: "Some value", description: "Custom desc", meaning: "Custom meaning"});
  }
