### ISSUE TITLE
Angular 9 No provider for InjectionToken TranslationsFormat!

### ISSUE THREAD

**Issue by vekunz** [ngx-translate/i18n-polyfill#88]
Hi, I updated our project to Angular 9. Now I have the problem that I get this runtime error in the browser:

```
NullInjectorError: R3InjectorError[AppModule -> RepositoryService -> ResourceStringsService -> I18n -> InjectionToken TranslationsFormat -> InjectionToken TranslationsFormat -> InjectionToken TranslationsFormat]: 
  NullInjectorError: No provider for InjectionToken TranslationsFormat!
```

The `AppModule`, the `RepositoryService` and the `ResourceStringsService` are from us.

In my angular.json I have this part for i18n configuration:
```
      "i18n": {
        "sourceLocale": "de",
        "locales": {
          "en": "src/i18n/dmsconfig.en.xlf"
        }
      }
```

**Comment by ocombe** [comment]
Hello, it makes sense, with ivy the i18n part of Angular has been completely rewritten from scratch, the provider `TranslationsFormat` does not exist anymore...
But you can use `$localize` from `@angular/localize` + [my new project `Locl`](https://github.com/loclapp/locl/) to do code translations
